name: short-sha-get-em
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:20.04']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get the short SHA
        id: getsha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Show it
        run:  echo ${{ steps.getsha.outputs.sha_short }} 
      - name: short sha via cut8
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Show cut8 sha
        run:  echo ${SHORT_SHA} 
