name: short-sha-get-em
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:20.04']
    steps:
      - name: Install git 
        run: |
             apt-get update
             apt-get install -y git
             git --version
             echo "Path is ... $PATH"
             PATH=$PATH:$(which git)
             echo "Path is ... $PATH"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get the short SHA
        id: revparse1
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Show revparse1
        run:  echo ${{ steps.revparse1.outputs.sha_short }} 
      - name: short sha via cut8
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Show cut8 sha
        run:  echo ${SHORT_SHA} 
      - name: rev-parse take 2
        id: getshaagain
        run: |
             calculatedSha=$(git rev-parse --short ${{ github.sha }})
             echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: show revparse2
        run: echo ${{ env.COMMIT_SHORT_SHA }}
